#ifndef __MyFrameDerived__
#define __MyFrameDerived__

/**
@file
Subclass of MyFrame, which is generated by wxFormBuilder.
*/

#include "gui/MyFrame.h"

//// end generated include

/** Implementing MyFrame */
class MyFrameDerived : public MyFrame
{
	public:
		/** Constructor */
		MyFrameDerived( wxWindow* parent );
	//// end generated class members

};

#endif // __MyFrameDerived__
